export const mockGenres = [
  { id: '1', name: 'Action' },
  { id: '2', name: 'Adventure' },
  { id: '3', name: 'Animation' },
  { id: '4', name: 'Comedy' },
  { id: '5', name: 'Crime' },
  { id: '6', name: 'Drama' },
  { id: '7', name: 'Horror' },
  { id: '8', name: 'Sci-Fi' },
  { id: '9', name: 'Thriller' },
  { id: '10', name: 'Romance' },
];

export const mockMovies = [
  {
    id: '1',
    title: 'The Dark Knight',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    releaseYear: 2008,
    runtime: 152,
    averageRating: 4.8,
    totalRatings: 2847,
    views: 15234,
    popularity: 95,
    genres: [mockGenres[0], mockGenres[5], mockGenres[8]],
    actors: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    director: 'Christopher Nolan',
    trailerUrl: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
  },
  {
    id: '2',
    title: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/9gk7admal4zl67YrxIo2AO08qX8.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
    releaseYear: 2010,
    runtime: 148,
    averageRating: 4.7,
    totalRatings: 2341,
    views: 12890,
    popularity: 92,
    genres: [mockGenres[1], mockGenres[7], mockGenres[8]],
    actors: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page'],
    director: 'Christopher Nolan',
    trailerUrl: 'https://www.youtube.com/watch?v=8hP9D6kZseM',
  },
  {
    id: '3',
    title: 'Interstellar',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniL6C9zBPNqQkRwVzYsGx.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    releaseYear: 2014,
    runtime: 169,
    averageRating: 4.6,
    totalRatings: 2156,
    views: 11234,
    popularity: 88,
    genres: [mockGenres[1], mockGenres[7], mockGenres[5]],
    actors: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    director: 'Christopher Nolan',
    trailerUrl: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
  },
  {
    id: '4',
    title: 'The Matrix',
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg',
    releaseYear: 1999,
    runtime: 136,
    averageRating: 4.7,
    totalRatings: 1987,
    views: 10567,
    popularity: 90,
    genres: [mockGenres[0], mockGenres[7], mockGenres[8]],
    actors: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    director: 'The Wachowskis',
    trailerUrl: 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
  },
  {
    id: '5',
    title: 'Pulp Fiction',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    releaseYear: 1994,
    runtime: 154,
    averageRating: 4.6,
    totalRatings: 1876,
    views: 9876,
    popularity: 85,
    genres: [mockGenres[4], mockGenres[5], mockGenres[3]],
    actors: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
    director: 'Quentin Tarantino',
    trailerUrl: 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
  },
  {
    id: '6',
    title: 'The Shawshank Redemption',
    description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    releaseYear: 1994,
    runtime: 142,
    averageRating: 4.9,
    totalRatings: 3456,
    views: 18234,
    popularity: 98,
    genres: [mockGenres[5]],
    actors: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'],
    director: 'Frank Darabont',
    trailerUrl: 'https://www.youtube.com/watch?v=6hB3S9bIaco',
  },
  {
    id: '7',
    title: 'Fight Club',
    description: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
    releaseYear: 1999,
    runtime: 139,
    averageRating: 4.5,
    totalRatings: 2134,
    views: 11567,
    popularity: 87,
    genres: [mockGenres[5], mockGenres[8]],
    actors: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'],
    director: 'David Fincher',
    trailerUrl: 'https://www.youtube.com/watch?v=SUXWAEXi0lY',
  },
  {
    id: '8',
    title: 'Forrest Gump',
    description: 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg',
    releaseYear: 1994,
    runtime: 142,
    averageRating: 4.6,
    totalRatings: 2345,
    views: 12345,
    popularity: 89,
    genres: [mockGenres[5], mockGenres[3]],
    actors: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
    director: 'Robert Zemeckis',
    trailerUrl: 'https://www.youtube.com/watch?v=bLvqoHBpjZA',
  },
  {
    id: '9',
    title: 'The Godfather',
    description: 'The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    releaseYear: 1972,
    runtime: 175,
    averageRating: 4.8,
    totalRatings: 2890,
    views: 14567,
    popularity: 94,
    genres: [mockGenres[4], mockGenres[5]],
    actors: ['Marlon Brando', 'Al Pacino', 'James Caan'],
    director: 'Francis Ford Coppola',
    trailerUrl: 'https://www.youtube.com/watch?v=sY1S34973zA',
  },
  {
    id: '10',
    title: 'Goodfellas',
    description: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
    releaseYear: 1990,
    runtime: 146,
    averageRating: 4.5,
    totalRatings: 1789,
    views: 9234,
    popularity: 82,
    genres: [mockGenres[4], mockGenres[5]],
    actors: ['Robert De Niro', 'Ray Liotta', 'Joe Pesci'],
    director: 'Martin Scorsese',
    trailerUrl: 'https://www.youtube.com/watch?v=qo5jJpHtI1Y',
  },
  {
    id: '11',
    title: 'The Silence of the Lambs',
    description: 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/61JRN3r2VfxrF7T9Mx4PT553Bq.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/r41xKlksLq81dQjx5ZGn7r4Mx0.jpg',
    releaseYear: 1991,
    runtime: 118,
    averageRating: 4.6,
    totalRatings: 1923,
    views: 10123,
    popularity: 86,
    genres: [mockGenres[4], mockGenres[6], mockGenres[8]],
    actors: ['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn'],
    director: 'Jonathan Demme',
    trailerUrl: 'https://www.youtube.com/watch?v=Ty4c5N1F8lI',
  },
  {
    id: '12',
    title: 'Saving Private Ryan',
    description: 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/mUkcucd2y4xPpmWPLF7PRei7K4X.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/8hGfA7U3H8YD8G8X8Y8X8Y8X8Y8X8Y8.jpg',
    releaseYear: 1998,
    runtime: 169,
    averageRating: 4.5,
    totalRatings: 1876,
    views: 9876,
    popularity: 84,
    genres: [mockGenres[0], mockGenres[5]],
    actors: ['Tom Hanks', 'Matt Damon', 'Tom Sizemore'],
    director: 'Steven Spielberg',
    trailerUrl: 'https://www.youtube.com/watch?v=9rG6hZ1Y8Y8',
  },
];

export const mockUser = {
  id: '1',
  email: 'admin@movie.com',
  username: 'admin',
  firstName: 'Admin',
  lastName: 'User',
  role: 'ADMIN',
  avatar: null,
  preferences: {
    preferredGenres: ['Action', 'Sci-Fi', 'Drama'],
    preferredActors: ['Leonardo DiCaprio', 'Christian Bale'],
    minRating: 4.0,
    language: 'en',
  },
};

export const mockWatchlist = [
  {
    id: '1',
    movieId: '2',
    status: 'PLANNED' as const,
    notes: 'Heard great things about it',
    movie: mockMovies[1],
  },
  {
    id: '2',
    movieId: '3',
    status: 'WATCHING' as const,
    notes: '',
    movie: mockMovies[2],
  },
];

export const mockHistory = [
  {
    id: '1',
    movieId: '1',
    watchedAt: '2024-01-15T10:30:00Z',
    watchDuration: 152,
    completed: true,
    movie: mockMovies[0],
  },
  {
    id: '2',
    movieId: '4',
    watchedAt: '2024-01-10T14:20:00Z',
    watchDuration: 120,
    completed: false,
    movie: mockMovies[3],
  },
];

export const mockRecommendations = [
  {
    id: '1',
    movieId: '5',
    score: 0.92,
    reason: 'Matches your preferred genres (Crime, Drama)',
    recommendationType: 'PERSONALIZED' as const,
    movie: mockMovies[4],
  },
  {
    id: '2',
    movieId: '6',
    score: 0.88,
    reason: 'Highly rated by users with similar taste',
    recommendationType: 'PERSONALIZED' as const,
    movie: mockMovies[5],
  },
  {
    id: '3',
    movieId: '7',
    score: 0.85,
    reason: 'Similar to movies you rated highly',
    recommendationType: 'SIMILAR' as const,
    movie: mockMovies[6],
  },
];
